service: mf-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  environment:
    BUCKET: ${ssm:main-bucket}
    WEATHER_API_TOKEN: ${ssm:weather-api-token}
    ALARM_API_TOKEN: ${ssm:alarm-api-token}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource: '*'
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${ssm:main-bucket}/*

functions:
  parseWeather:
    handler: dist/functions/parse-weather/handler.handler
    timeout: 15
    memorySize: 128
    events:
      - schedule: rate(24 hours)
      - http:
          path: /parseWeather
          method: post
  parseIsw:
    handler: dist/functions/isw/handler.handler
    timeout: 900
    memorySize: 256
    events:
      - schedule: rate(24 hours)
  parseAlarms:
    handler: dist/functions/alarms/handler.handler
    timeout: 30
    memorySize: 128
    events:
      - schedule: rate(24 hours)
      - http:
          path: /alarms
          method: post
