service: mf-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  environment:
    BUCKET: ${ssm:main-bucket}
    WEATHER_API_TOKEN: ${ssm:weather-api-token}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource: '*'
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${ssm:main-bucket}/*

functions:
  parseWeather:
    handler: dist/src/functions/parse-weather/handler.handler
    timeout: 15
    memorySize: 128
    events:
      - schedule:
          rate: (0 0 * * *)
          timezone: Europe/Kiev
      - http:
          path: /parseWeather
          method: post
plugins:
  - serverless-local-schedule
